### ISSUE TITLE
Keep showing this error: KeyError: 'tweet_id'.

### ISSUE THREAD

**Issue by ziw42** [MuMiN-dataset/mumin-build#11] opened 2022-07-08 04:13 UTC
Hi! Thank you for your wonderful work! I ran the tutorial on Colab but when I want to run the same code on my own laptop (Compile the dataset), it always shows this: "KeyError: 'tweet_id'".
<img width="1216" alt="微信图片_20220708001238" src="https://user-images.githubusercontent.com/89410855/177915524-b0933bc5-f5d5-41dd-af6c-8bddc38e1f55.png">

I am using python 3.9 and pycharm as my IDE. Any idea why this is happening? Thanks a lot for your help!

**Comment by saattrupdan** [comment] 2022-07-08 11:01
Hiya and thanks for your interest! Can you double check whether you have specified a correct Twitter Bearer Token?

**Comment by Yutaaa76** [comment] 2022-07-17 22:24
> Hiya and thanks for your interest! Can you double check whether you have specified a correct Twitter Bearer Token?

Hiya, I got the same error when compiling the dataset on my Windows laptop and definitely with the correct Twitter Token, and I'm using python 3.8.10. 
I found that this error won't happen in Colab or Kaggle notebook. I'm using MuMiN for my dissertation project, so I have to compile the dataset on Colab then download it to my local device, but compiling it on Cloab is too slow, especially for the large size dataset.

**Comment by saattrupdan** [comment] 2022-07-18 12:20
@Yutaaa76 @ziw42
Can you try to install the development version of the package via `pip install git+https://github.com/MuMiN-dataset/mumin-build@dev` and see if the problem persists? I cannot recreate the error you're getting with the negative tweet IDs, but I'm just forcing all tweet IDs to be positive now.

**Comment by saattrupdan** [comment] 2022-07-18 14:16
This seems to be a duplicate of https://github.com/MuMiN-dataset/mumin-build/issues/12.

This is a Windows problem - we're currently trying to fix it in the other issue.

**Comment by saattrupdan** [comment] 2022-07-22 10:54
Fixed in https://github.com/MuMiN-dataset/mumin-build/releases/tag/v1.9.0, closing. Please open a new issue if the problem (or others) persist 🙂

**Closed by saattrupdan** 2022-07-22 10:54 UTC
Labels: bug, duplicate
